// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/project.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_SECRET_TYPE_UNKNOWN     SecretType = 0 // Всегда начинай с 0 и UNKNOWN
	SecretType_SECRET_TYPE_CREDENTIALS SecretType = 1
	SecretType_SECRET_TYPE_CARD        SecretType = 2
	SecretType_SECRET_TYPE_TEXT        SecretType = 3
	SecretType_SECRET_TYPE_FILE        SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNKNOWN",
		1: "SECRET_TYPE_CREDENTIALS",
		2: "SECRET_TYPE_CARD",
		3: "SECRET_TYPE_TEXT",
		4: "SECRET_TYPE_FILE",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNKNOWN":     0,
		"SECRET_TYPE_CREDENTIALS": 1,
		"SECRET_TYPE_CARD":        2,
		"SECRET_TYPE_TEXT":        3,
		"SECRET_TYPE_FILE":        4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_project_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_api_project_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{0}
}

type CredentialsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsPayload) Reset() {
	*x = CredentialsPayload{}
	mi := &file_api_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsPayload) ProtoMessage() {}

func (x *CredentialsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsPayload.ProtoReflect.Descriptor instead.
func (*CredentialsPayload) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsPayload) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CredentialsPayload) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CredentialsPayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CredentialsPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CardPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	Expiry        string                 `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"` // MM/YY
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardPayload) Reset() {
	*x = CardPayload{}
	mi := &file_api_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPayload) ProtoMessage() {}

func (x *CardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardPayload.ProtoReflect.Descriptor instead.
func (*CardPayload) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{1}
}

func (x *CardPayload) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardPayload) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *CardPayload) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CardPayload) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

type TextPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // Сам текст заметки
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_api_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPayload.ProtoReflect.Descriptor instead.
func (*TextPayload) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{2}
}

func (x *TextPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FilePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"` // "Не открывать до 2025 года"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePayload) Reset() {
	*x = FilePayload{}
	mi := &file_api_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePayload) ProtoMessage() {}

func (x *FilePayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePayload.ProtoReflect.Descriptor instead.
func (*FilePayload) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{3}
}

func (x *FilePayload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FilePayload) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*CreateSecretRequest_Metadata
	//	*CreateSecretRequest_ChunkData
	Data          isCreateSecretRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_api_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSecretRequest) GetData() isCreateSecretRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateSecretRequest) GetMetadata() *SecretMetadata {
	if x != nil {
		if x, ok := x.Data.(*CreateSecretRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *CreateSecretRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*CreateSecretRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isCreateSecretRequest_Data interface {
	isCreateSecretRequest_Data()
}

type CreateSecretRequest_Metadata struct {
	Metadata *SecretMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type CreateSecretRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*CreateSecretRequest_Metadata) isCreateSecretRequest_Data() {}

func (*CreateSecretRequest_ChunkData) isCreateSecretRequest_Data() {}

type SecretMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=project.SecretType" json:"type,omitempty"`
	PublicMeta    map[string]string      `protobuf:"bytes,3,rep,name=public_meta,json=publicMeta,proto3" json:"public_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMetadata) Reset() {
	*x = SecretMetadata{}
	mi := &file_api_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMetadata) ProtoMessage() {}

func (x *SecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMetadata.ProtoReflect.Descriptor instead.
func (*SecretMetadata) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{9}
}

func (x *SecretMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretMetadata) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_SECRET_TYPE_UNKNOWN
}

func (x *SecretMetadata) GetPublicMeta() map[string]string {
	if x != nil {
		return x.PublicMeta
	}
	return nil
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_api_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSecretResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSecretResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Get One
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{13}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *SecretMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // Зашифрованный блоб целиком (для маленьких файлов)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{14}
}

func (x *GetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResponse) GetMetadata() *SecretMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetResponse) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Пагинация
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_api_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{15}
}

func (x *GetListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretItem          `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListResponse) Reset() {
	*x = GetListResponse{}
	mi := &file_api_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListResponse) ProtoMessage() {}

func (x *GetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListResponse.ProtoReflect.Descriptor instead.
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{16}
}

func (x *GetListResponse) GetSecrets() []*SecretItem {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *GetListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SecretItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *SecretMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // Тут удобно показать Name, Type и PublicMeta
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretItem) Reset() {
	*x = SecretItem{}
	mi := &file_api_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretItem) ProtoMessage() {}

func (x *SecretItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretItem.ProtoReflect.Descriptor instead.
func (*SecretItem) Descriptor() ([]byte, []int) {
	return file_api_project_proto_rawDescGZIP(), []int{17}
}

func (x *SecretItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretItem) GetMetadata() *SecretMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_project_proto protoreflect.FileDescriptor

const file_api_project_proto_rawDesc = "" +
	"\n" +
	"\x11api/project.proto\x12\aproject\"z\n" +
	"\x12CredentialsPayload\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"g\n" +
	"\vCardPayload\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\"C\n" +
	"\vTextPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"C\n" +
	"\vFilePayload\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Z\n" +
	"\x10RegisterResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"u\n" +
	"\x13CreateSecretRequest\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.project.SecretMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"\xd6\x01\n" +
	"\x0eSecretMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.project.SecretTypeR\x04type\x12H\n" +
	"\vpublic_meta\x18\x03 \x03(\v2'.project.SecretMetadata.PublicMetaEntryR\n" +
	"publicMeta\x1a=\n" +
	"\x0fPublicMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x14CreateSecretResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x0eDeleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\vGetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.project.SecretMetadataR\bmetadata\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\">\n" +
	"\x0eGetListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"a\n" +
	"\x0fGetListResponse\x12-\n" +
	"\asecrets\x18\x01 \x03(\v2\x13.project.SecretItemR\asecrets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Q\n" +
	"\n" +
	"SecretItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.project.SecretMetadataR\bmetadata*\x84\x01\n" +
	"\n" +
	"SecretType\x12\x17\n" +
	"\x13SECRET_TYPE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17SECRET_TYPE_CREDENTIALS\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_CARD\x10\x02\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x03\x12\x14\n" +
	"\x10SECRET_TYPE_FILE\x10\x042\x95\x03\n" +
	"\x0eProjectService\x12?\n" +
	"\bRegister\x12\x18.project.RegisterRequest\x1a\x19.project.RegisterResponse\x126\n" +
	"\x05Login\x12\x15.project.LoginRequest\x1a\x16.project.LoginResponse\x12M\n" +
	"\fCreateSecret\x12\x1c.project.CreateSecretRequest\x1a\x1d.project.CreateSecretResponse(\x01\x12?\n" +
	"\fDeleteSecret\x12\x16.project.DeleteRequest\x1a\x17.project.DeleteResponse\x126\n" +
	"\tGetSecret\x12\x13.project.GetRequest\x1a\x14.project.GetResponse\x12B\n" +
	"\rGetSecretList\x12\x17.project.GetListRequest\x1a\x18.project.GetListResponseB\x1aZ\x18secretKeeper/pkg/api;apib\x06proto3"

var (
	file_api_project_proto_rawDescOnce sync.Once
	file_api_project_proto_rawDescData []byte
)

func file_api_project_proto_rawDescGZIP() []byte {
	file_api_project_proto_rawDescOnce.Do(func() {
		file_api_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_project_proto_rawDesc), len(file_api_project_proto_rawDesc)))
	})
	return file_api_project_proto_rawDescData
}

var file_api_project_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_project_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_project_proto_goTypes = []any{
	(SecretType)(0),              // 0: project.SecretType
	(*CredentialsPayload)(nil),   // 1: project.CredentialsPayload
	(*CardPayload)(nil),          // 2: project.CardPayload
	(*TextPayload)(nil),          // 3: project.TextPayload
	(*FilePayload)(nil),          // 4: project.FilePayload
	(*RegisterRequest)(nil),      // 5: project.RegisterRequest
	(*RegisterResponse)(nil),     // 6: project.RegisterResponse
	(*LoginRequest)(nil),         // 7: project.LoginRequest
	(*LoginResponse)(nil),        // 8: project.LoginResponse
	(*CreateSecretRequest)(nil),  // 9: project.CreateSecretRequest
	(*SecretMetadata)(nil),       // 10: project.SecretMetadata
	(*CreateSecretResponse)(nil), // 11: project.CreateSecretResponse
	(*DeleteRequest)(nil),        // 12: project.DeleteRequest
	(*DeleteResponse)(nil),       // 13: project.DeleteResponse
	(*GetRequest)(nil),           // 14: project.GetRequest
	(*GetResponse)(nil),          // 15: project.GetResponse
	(*GetListRequest)(nil),       // 16: project.GetListRequest
	(*GetListResponse)(nil),      // 17: project.GetListResponse
	(*SecretItem)(nil),           // 18: project.SecretItem
	nil,                          // 19: project.SecretMetadata.PublicMetaEntry
}
var file_api_project_proto_depIdxs = []int32{
	10, // 0: project.CreateSecretRequest.metadata:type_name -> project.SecretMetadata
	0,  // 1: project.SecretMetadata.type:type_name -> project.SecretType
	19, // 2: project.SecretMetadata.public_meta:type_name -> project.SecretMetadata.PublicMetaEntry
	10, // 3: project.GetResponse.metadata:type_name -> project.SecretMetadata
	18, // 4: project.GetListResponse.secrets:type_name -> project.SecretItem
	10, // 5: project.SecretItem.metadata:type_name -> project.SecretMetadata
	5,  // 6: project.ProjectService.Register:input_type -> project.RegisterRequest
	7,  // 7: project.ProjectService.Login:input_type -> project.LoginRequest
	9,  // 8: project.ProjectService.CreateSecret:input_type -> project.CreateSecretRequest
	12, // 9: project.ProjectService.DeleteSecret:input_type -> project.DeleteRequest
	14, // 10: project.ProjectService.GetSecret:input_type -> project.GetRequest
	16, // 11: project.ProjectService.GetSecretList:input_type -> project.GetListRequest
	6,  // 12: project.ProjectService.Register:output_type -> project.RegisterResponse
	8,  // 13: project.ProjectService.Login:output_type -> project.LoginResponse
	11, // 14: project.ProjectService.CreateSecret:output_type -> project.CreateSecretResponse
	13, // 15: project.ProjectService.DeleteSecret:output_type -> project.DeleteResponse
	15, // 16: project.ProjectService.GetSecret:output_type -> project.GetResponse
	17, // 17: project.ProjectService.GetSecretList:output_type -> project.GetListResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_project_proto_init() }
func file_api_project_proto_init() {
	if File_api_project_proto != nil {
		return
	}
	file_api_project_proto_msgTypes[8].OneofWrappers = []any{
		(*CreateSecretRequest_Metadata)(nil),
		(*CreateSecretRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_project_proto_rawDesc), len(file_api_project_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_project_proto_goTypes,
		DependencyIndexes: file_api_project_proto_depIdxs,
		EnumInfos:         file_api_project_proto_enumTypes,
		MessageInfos:      file_api_project_proto_msgTypes,
	}.Build()
	File_api_project_proto = out.File
	file_api_project_proto_goTypes = nil
	file_api_project_proto_depIdxs = nil
}
